spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
